services:
  backend:
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./algorithms:/home/node/app/algorithms
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - backend/.env
    networks:
      - back

  frontend:
    container_name: frontend
    restart: always
    ports:
      - "3001:5173"
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file:
      - frontend/.env
    networks:
      - back

networks:
  back:
    driver: bridge
