services:
  backend:
    container_name: backend
    restart: always
    ports:
      - '3000:3000'
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - /src/bin:/home/node/app
    networks:
      - back

networks:
  back:
    driver: bridge
