FROM node:18-alpine

USER root

WORKDIR /home/node/app

RUN npm install --include=optional -g @nestjs/cli

RUN apk update && \
    apk add --no-cache gcc musl-dev

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
