FROM node:18-alpine

WORKDIR /home/node/app

COPY . .

RUN apk update && \
    apk add --no-cache gcc musl-dev

# RUN gcc /home/node/app/algorithms/logicalExpressionEvaluator.c -o /home/node/app/src/bin/logicalExpressionEvaluator

RUN npm install --include=optional -g @nestjs/cli

RUN npm install

EXPOSE 3001

CMD ["npm", "run", "start:dev"]
